{
    "word": "Cask",
    "definitions": [
        "A barrel-shaped vessel made of staves headings, and hoops, usually fitted together so as to hold liquids. It may be larger or smaller than a barrel.",
        "The quantity contained in a cask.",
        "A casket; a small box for jewels.",
        "To put into a cask."
    ],
    "examples": [
    ],
    "etymology": null
}